//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2015/8/15 11:17:42
namespace Tulipe.bsc.Bing
{
    
    /// <summary>
    /// There are no comments for BingSearchContainer in the schema.
    /// </summary>
    public partial class BingSearchContainer : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new BingSearchContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public BingSearchContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Bing", "Tulipe.bsc.Bing");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Tulipe.bsc.Bing", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Bing.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for ExpandableSearchResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ExpandableSearchResult> ExpandableSearchResultSet
        {
            get
            {
                if ((this._ExpandableSearchResultSet == null))
                {
                    this._ExpandableSearchResultSet = base.CreateQuery<ExpandableSearchResult>("ExpandableSearchResultSet");
                }
                return this._ExpandableSearchResultSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ExpandableSearchResult> _ExpandableSearchResultSet;
        /// <summary>
        /// There are no comments for WebResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<WebResult> WebResultSet
        {
            get
            {
                if ((this._WebResultSet == null))
                {
                    this._WebResultSet = base.CreateQuery<WebResult>("WebResultSet");
                }
                return this._WebResultSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<WebResult> _WebResultSet;
        /// <summary>
        /// There are no comments for ImageResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ImageResult> ImageResultSet
        {
            get
            {
                if ((this._ImageResultSet == null))
                {
                    this._ImageResultSet = base.CreateQuery<ImageResult>("ImageResultSet");
                }
                return this._ImageResultSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ImageResult> _ImageResultSet;
        /// <summary>
        /// There are no comments for VideoResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<VideoResult> VideoResultSet
        {
            get
            {
                if ((this._VideoResultSet == null))
                {
                    this._VideoResultSet = base.CreateQuery<VideoResult>("VideoResultSet");
                }
                return this._VideoResultSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<VideoResult> _VideoResultSet;
        /// <summary>
        /// There are no comments for NewsResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<NewsResult> NewsResultSet
        {
            get
            {
                if ((this._NewsResultSet == null))
                {
                    this._NewsResultSet = base.CreateQuery<NewsResult>("NewsResultSet");
                }
                return this._NewsResultSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<NewsResult> _NewsResultSet;
        /// <summary>
        /// There are no comments for RelatedSearchResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RelatedSearchResult> RelatedSearchResultSet
        {
            get
            {
                if ((this._RelatedSearchResultSet == null))
                {
                    this._RelatedSearchResultSet = base.CreateQuery<RelatedSearchResult>("RelatedSearchResultSet");
                }
                return this._RelatedSearchResultSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RelatedSearchResult> _RelatedSearchResultSet;
        /// <summary>
        /// There are no comments for SpellResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SpellResult> SpellResultSet
        {
            get
            {
                if ((this._SpellResultSet == null))
                {
                    this._SpellResultSet = base.CreateQuery<SpellResult>("SpellResultSet");
                }
                return this._SpellResultSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SpellResult> _SpellResultSet;
        /// <summary>
        /// There are no comments for ExpandableSearchResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToExpandableSearchResultSet(ExpandableSearchResult expandableSearchResult)
        {
            base.AddObject("ExpandableSearchResultSet", expandableSearchResult);
        }
        /// <summary>
        /// There are no comments for WebResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToWebResultSet(WebResult webResult)
        {
            base.AddObject("WebResultSet", webResult);
        }
        /// <summary>
        /// There are no comments for ImageResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToImageResultSet(ImageResult imageResult)
        {
            base.AddObject("ImageResultSet", imageResult);
        }
        /// <summary>
        /// There are no comments for VideoResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToVideoResultSet(VideoResult videoResult)
        {
            base.AddObject("VideoResultSet", videoResult);
        }
        /// <summary>
        /// There are no comments for NewsResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNewsResultSet(NewsResult newsResult)
        {
            base.AddObject("NewsResultSet", newsResult);
        }
        /// <summary>
        /// There are no comments for RelatedSearchResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRelatedSearchResultSet(RelatedSearchResult relatedSearchResult)
        {
            base.AddObject("RelatedSearchResultSet", relatedSearchResult);
        }
        /// <summary>
        /// There are no comments for SpellResultSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSpellResultSet(SpellResult spellResult)
        {
            base.AddObject("SpellResultSet", spellResult);
        }
    }
    /// <summary>
    /// There are no comments for Bing.ExpandableSearchResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ExpandableSearchResultSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class ExpandableSearchResult : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ExpandableSearchResult object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ExpandableSearchResult CreateExpandableSearchResult(global::System.Guid ID)
        {
            ExpandableSearchResult expandableSearchResult = new ExpandableSearchResult();
            expandableSearchResult.ID = ID;
            return expandableSearchResult;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property WebTotal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> WebTotal
        {
            get
            {
                return this._WebTotal;
            }
            set
            {
                this.OnWebTotalChanging(value);
                this._WebTotal = value;
                this.OnWebTotalChanged();
                this.OnPropertyChanged("WebTotal");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _WebTotal;
        partial void OnWebTotalChanging(global::System.Nullable<long> value);
        partial void OnWebTotalChanged();
        /// <summary>
        /// There are no comments for Property WebOffset in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> WebOffset
        {
            get
            {
                return this._WebOffset;
            }
            set
            {
                this.OnWebOffsetChanging(value);
                this._WebOffset = value;
                this.OnWebOffsetChanged();
                this.OnPropertyChanged("WebOffset");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _WebOffset;
        partial void OnWebOffsetChanging(global::System.Nullable<long> value);
        partial void OnWebOffsetChanged();
        /// <summary>
        /// There are no comments for Property ImageTotal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> ImageTotal
        {
            get
            {
                return this._ImageTotal;
            }
            set
            {
                this.OnImageTotalChanging(value);
                this._ImageTotal = value;
                this.OnImageTotalChanged();
                this.OnPropertyChanged("ImageTotal");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _ImageTotal;
        partial void OnImageTotalChanging(global::System.Nullable<long> value);
        partial void OnImageTotalChanged();
        /// <summary>
        /// There are no comments for Property ImageOffset in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> ImageOffset
        {
            get
            {
                return this._ImageOffset;
            }
            set
            {
                this.OnImageOffsetChanging(value);
                this._ImageOffset = value;
                this.OnImageOffsetChanged();
                this.OnPropertyChanged("ImageOffset");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _ImageOffset;
        partial void OnImageOffsetChanging(global::System.Nullable<long> value);
        partial void OnImageOffsetChanged();
        /// <summary>
        /// There are no comments for Property VideoTotal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> VideoTotal
        {
            get
            {
                return this._VideoTotal;
            }
            set
            {
                this.OnVideoTotalChanging(value);
                this._VideoTotal = value;
                this.OnVideoTotalChanged();
                this.OnPropertyChanged("VideoTotal");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _VideoTotal;
        partial void OnVideoTotalChanging(global::System.Nullable<long> value);
        partial void OnVideoTotalChanged();
        /// <summary>
        /// There are no comments for Property VideoOffset in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> VideoOffset
        {
            get
            {
                return this._VideoOffset;
            }
            set
            {
                this.OnVideoOffsetChanging(value);
                this._VideoOffset = value;
                this.OnVideoOffsetChanged();
                this.OnPropertyChanged("VideoOffset");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _VideoOffset;
        partial void OnVideoOffsetChanging(global::System.Nullable<long> value);
        partial void OnVideoOffsetChanged();
        /// <summary>
        /// There are no comments for Property NewsTotal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> NewsTotal
        {
            get
            {
                return this._NewsTotal;
            }
            set
            {
                this.OnNewsTotalChanging(value);
                this._NewsTotal = value;
                this.OnNewsTotalChanged();
                this.OnPropertyChanged("NewsTotal");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _NewsTotal;
        partial void OnNewsTotalChanging(global::System.Nullable<long> value);
        partial void OnNewsTotalChanged();
        /// <summary>
        /// There are no comments for Property NewsOffset in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> NewsOffset
        {
            get
            {
                return this._NewsOffset;
            }
            set
            {
                this.OnNewsOffsetChanging(value);
                this._NewsOffset = value;
                this.OnNewsOffsetChanged();
                this.OnPropertyChanged("NewsOffset");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _NewsOffset;
        partial void OnNewsOffsetChanging(global::System.Nullable<long> value);
        partial void OnNewsOffsetChanged();
        /// <summary>
        /// There are no comments for Property SpellingSuggestionsTotal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> SpellingSuggestionsTotal
        {
            get
            {
                return this._SpellingSuggestionsTotal;
            }
            set
            {
                this.OnSpellingSuggestionsTotalChanging(value);
                this._SpellingSuggestionsTotal = value;
                this.OnSpellingSuggestionsTotalChanged();
                this.OnPropertyChanged("SpellingSuggestionsTotal");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _SpellingSuggestionsTotal;
        partial void OnSpellingSuggestionsTotalChanging(global::System.Nullable<long> value);
        partial void OnSpellingSuggestionsTotalChanged();
        /// <summary>
        /// There are no comments for Property AlteredQuery in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AlteredQuery
        {
            get
            {
                return this._AlteredQuery;
            }
            set
            {
                this.OnAlteredQueryChanging(value);
                this._AlteredQuery = value;
                this.OnAlteredQueryChanged();
                this.OnPropertyChanged("AlteredQuery");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AlteredQuery;
        partial void OnAlteredQueryChanging(string value);
        partial void OnAlteredQueryChanged();
        /// <summary>
        /// There are no comments for Property AlterationOverrideQuery in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AlterationOverrideQuery
        {
            get
            {
                return this._AlterationOverrideQuery;
            }
            set
            {
                this.OnAlterationOverrideQueryChanging(value);
                this._AlterationOverrideQuery = value;
                this.OnAlterationOverrideQueryChanged();
                this.OnPropertyChanged("AlterationOverrideQuery");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AlterationOverrideQuery;
        partial void OnAlterationOverrideQueryChanging(string value);
        partial void OnAlterationOverrideQueryChanged();
        /// <summary>
        /// There are no comments for Web in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<WebResult> Web
        {
            get
            {
                return this._Web;
            }
            set
            {
                this._Web = value;
                this.OnPropertyChanged("Web");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<WebResult> _Web = new global::System.Data.Services.Client.DataServiceCollection<WebResult>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Image in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ImageResult> Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this._Image = value;
                this.OnPropertyChanged("Image");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ImageResult> _Image = new global::System.Data.Services.Client.DataServiceCollection<ImageResult>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Video in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<VideoResult> Video
        {
            get
            {
                return this._Video;
            }
            set
            {
                this._Video = value;
                this.OnPropertyChanged("Video");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<VideoResult> _Video = new global::System.Data.Services.Client.DataServiceCollection<VideoResult>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for News in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<NewsResult> News
        {
            get
            {
                return this._News;
            }
            set
            {
                this._News = value;
                this.OnPropertyChanged("News");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<NewsResult> _News = new global::System.Data.Services.Client.DataServiceCollection<NewsResult>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for RelatedSearch in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RelatedSearchResult> RelatedSearch
        {
            get
            {
                return this._RelatedSearch;
            }
            set
            {
                this._RelatedSearch = value;
                this.OnPropertyChanged("RelatedSearch");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RelatedSearchResult> _RelatedSearch = new global::System.Data.Services.Client.DataServiceCollection<RelatedSearchResult>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for SpellingSuggestions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SpellResult> SpellingSuggestions
        {
            get
            {
                return this._SpellingSuggestions;
            }
            set
            {
                this._SpellingSuggestions = value;
                this.OnPropertyChanged("SpellingSuggestions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SpellResult> _SpellingSuggestions = new global::System.Data.Services.Client.DataServiceCollection<SpellResult>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Bing.WebResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("WebResultSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class WebResult : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new WebResult object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static WebResult CreateWebResult(global::System.Guid ID)
        {
            WebResult webResult = new WebResult();
            webResult.ID = ID;
            return webResult;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property DisplayUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DisplayUrl
        {
            get
            {
                return this._DisplayUrl;
            }
            set
            {
                this.OnDisplayUrlChanging(value);
                this._DisplayUrl = value;
                this.OnDisplayUrlChanged();
                this.OnPropertyChanged("DisplayUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DisplayUrl;
        partial void OnDisplayUrlChanging(string value);
        partial void OnDisplayUrlChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this._Url = value;
                this.OnUrlChanged();
                this.OnPropertyChanged("Url");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType Bing.Thumbnail in the schema.
    /// </summary>
    public partial class Thumbnail : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property MediaUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MediaUrl
        {
            get
            {
                return this._MediaUrl;
            }
            set
            {
                this.OnMediaUrlChanging(value);
                this._MediaUrl = value;
                this.OnMediaUrlChanged();
                this.OnPropertyChanged("MediaUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MediaUrl;
        partial void OnMediaUrlChanging(string value);
        partial void OnMediaUrlChanged();
        /// <summary>
        /// There are no comments for Property ContentType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ContentType
        {
            get
            {
                return this._ContentType;
            }
            set
            {
                this.OnContentTypeChanging(value);
                this._ContentType = value;
                this.OnContentTypeChanged();
                this.OnPropertyChanged("ContentType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ContentType;
        partial void OnContentTypeChanging(string value);
        partial void OnContentTypeChanged();
        /// <summary>
        /// There are no comments for Property Width in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Width
        {
            get
            {
                return this._Width;
            }
            set
            {
                this.OnWidthChanging(value);
                this._Width = value;
                this.OnWidthChanged();
                this.OnPropertyChanged("Width");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Width;
        partial void OnWidthChanging(global::System.Nullable<int> value);
        partial void OnWidthChanged();
        /// <summary>
        /// There are no comments for Property Height in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this.OnHeightChanging(value);
                this._Height = value;
                this.OnHeightChanged();
                this.OnPropertyChanged("Height");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Height;
        partial void OnHeightChanging(global::System.Nullable<int> value);
        partial void OnHeightChanged();
        /// <summary>
        /// There are no comments for Property FileSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> FileSize
        {
            get
            {
                return this._FileSize;
            }
            set
            {
                this.OnFileSizeChanging(value);
                this._FileSize = value;
                this.OnFileSizeChanged();
                this.OnPropertyChanged("FileSize");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _FileSize;
        partial void OnFileSizeChanging(global::System.Nullable<long> value);
        partial void OnFileSizeChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Bing.ImageResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ImageResultSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class ImageResult : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ImageResult object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ImageResult CreateImageResult(global::System.Guid ID)
        {
            ImageResult imageResult = new ImageResult();
            imageResult.ID = ID;
            return imageResult;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property MediaUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MediaUrl
        {
            get
            {
                return this._MediaUrl;
            }
            set
            {
                this.OnMediaUrlChanging(value);
                this._MediaUrl = value;
                this.OnMediaUrlChanged();
                this.OnPropertyChanged("MediaUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MediaUrl;
        partial void OnMediaUrlChanging(string value);
        partial void OnMediaUrlChanged();
        /// <summary>
        /// There are no comments for Property SourceUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SourceUrl
        {
            get
            {
                return this._SourceUrl;
            }
            set
            {
                this.OnSourceUrlChanging(value);
                this._SourceUrl = value;
                this.OnSourceUrlChanged();
                this.OnPropertyChanged("SourceUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SourceUrl;
        partial void OnSourceUrlChanging(string value);
        partial void OnSourceUrlChanged();
        /// <summary>
        /// There are no comments for Property DisplayUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DisplayUrl
        {
            get
            {
                return this._DisplayUrl;
            }
            set
            {
                this.OnDisplayUrlChanging(value);
                this._DisplayUrl = value;
                this.OnDisplayUrlChanged();
                this.OnPropertyChanged("DisplayUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DisplayUrl;
        partial void OnDisplayUrlChanging(string value);
        partial void OnDisplayUrlChanged();
        /// <summary>
        /// There are no comments for Property Width in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Width
        {
            get
            {
                return this._Width;
            }
            set
            {
                this.OnWidthChanging(value);
                this._Width = value;
                this.OnWidthChanged();
                this.OnPropertyChanged("Width");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Width;
        partial void OnWidthChanging(global::System.Nullable<int> value);
        partial void OnWidthChanged();
        /// <summary>
        /// There are no comments for Property Height in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this.OnHeightChanging(value);
                this._Height = value;
                this.OnHeightChanged();
                this.OnPropertyChanged("Height");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Height;
        partial void OnHeightChanging(global::System.Nullable<int> value);
        partial void OnHeightChanged();
        /// <summary>
        /// There are no comments for Property FileSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> FileSize
        {
            get
            {
                return this._FileSize;
            }
            set
            {
                this.OnFileSizeChanging(value);
                this._FileSize = value;
                this.OnFileSizeChanged();
                this.OnPropertyChanged("FileSize");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _FileSize;
        partial void OnFileSizeChanging(global::System.Nullable<long> value);
        partial void OnFileSizeChanged();
        /// <summary>
        /// There are no comments for Property ContentType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ContentType
        {
            get
            {
                return this._ContentType;
            }
            set
            {
                this.OnContentTypeChanging(value);
                this._ContentType = value;
                this.OnContentTypeChanged();
                this.OnPropertyChanged("ContentType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ContentType;
        partial void OnContentTypeChanging(string value);
        partial void OnContentTypeChanged();
        /// <summary>
        /// There are no comments for Property Thumbnail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Thumbnail Thumbnail
        {
            get
            {
                if (((this._Thumbnail == null) 
                            && (this._ThumbnailInitialized != true)))
                {
                    this._Thumbnail = new Thumbnail();
                    this._ThumbnailInitialized = true;
                }
                return this._Thumbnail;
            }
            set
            {
                this.OnThumbnailChanging(value);
                this._Thumbnail = value;
                this._ThumbnailInitialized = true;
                this.OnThumbnailChanged();
                this.OnPropertyChanged("Thumbnail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Thumbnail _Thumbnail;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _ThumbnailInitialized;
        partial void OnThumbnailChanging(Thumbnail value);
        partial void OnThumbnailChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Bing.VideoResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("VideoResultSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class VideoResult : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new VideoResult object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static VideoResult CreateVideoResult(global::System.Guid ID)
        {
            VideoResult videoResult = new VideoResult();
            videoResult.ID = ID;
            return videoResult;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property MediaUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MediaUrl
        {
            get
            {
                return this._MediaUrl;
            }
            set
            {
                this.OnMediaUrlChanging(value);
                this._MediaUrl = value;
                this.OnMediaUrlChanged();
                this.OnPropertyChanged("MediaUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MediaUrl;
        partial void OnMediaUrlChanging(string value);
        partial void OnMediaUrlChanged();
        /// <summary>
        /// There are no comments for Property DisplayUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DisplayUrl
        {
            get
            {
                return this._DisplayUrl;
            }
            set
            {
                this.OnDisplayUrlChanging(value);
                this._DisplayUrl = value;
                this.OnDisplayUrlChanged();
                this.OnPropertyChanged("DisplayUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DisplayUrl;
        partial void OnDisplayUrlChanging(string value);
        partial void OnDisplayUrlChanged();
        /// <summary>
        /// There are no comments for Property RunTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> RunTime
        {
            get
            {
                return this._RunTime;
            }
            set
            {
                this.OnRunTimeChanging(value);
                this._RunTime = value;
                this.OnRunTimeChanged();
                this.OnPropertyChanged("RunTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _RunTime;
        partial void OnRunTimeChanging(global::System.Nullable<int> value);
        partial void OnRunTimeChanged();
        /// <summary>
        /// There are no comments for Property Thumbnail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Thumbnail Thumbnail
        {
            get
            {
                if (((this._Thumbnail == null) 
                            && (this._ThumbnailInitialized != true)))
                {
                    this._Thumbnail = new Thumbnail();
                    this._ThumbnailInitialized = true;
                }
                return this._Thumbnail;
            }
            set
            {
                this.OnThumbnailChanging(value);
                this._Thumbnail = value;
                this._ThumbnailInitialized = true;
                this.OnThumbnailChanged();
                this.OnPropertyChanged("Thumbnail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Thumbnail _Thumbnail;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _ThumbnailInitialized;
        partial void OnThumbnailChanging(Thumbnail value);
        partial void OnThumbnailChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Bing.NewsResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("NewsResultSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class NewsResult : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new NewsResult object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NewsResult CreateNewsResult(global::System.Guid ID)
        {
            NewsResult newsResult = new NewsResult();
            newsResult.ID = ID;
            return newsResult;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this._Url = value;
                this.OnUrlChanged();
                this.OnPropertyChanged("Url");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        /// <summary>
        /// There are no comments for Property Source in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Source
        {
            get
            {
                return this._Source;
            }
            set
            {
                this.OnSourceChanging(value);
                this._Source = value;
                this.OnSourceChanged();
                this.OnPropertyChanged("Source");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Source;
        partial void OnSourceChanging(string value);
        partial void OnSourceChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Bing.RelatedSearchResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("RelatedSearchResultSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class RelatedSearchResult : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RelatedSearchResult object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RelatedSearchResult CreateRelatedSearchResult(global::System.Guid ID)
        {
            RelatedSearchResult relatedSearchResult = new RelatedSearchResult();
            relatedSearchResult.ID = ID;
            return relatedSearchResult;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property BingUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BingUrl
        {
            get
            {
                return this._BingUrl;
            }
            set
            {
                this.OnBingUrlChanging(value);
                this._BingUrl = value;
                this.OnBingUrlChanged();
                this.OnPropertyChanged("BingUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BingUrl;
        partial void OnBingUrlChanging(string value);
        partial void OnBingUrlChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Bing.SpellResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SpellResultSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class SpellResult : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SpellResult object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SpellResult CreateSpellResult(global::System.Guid ID)
        {
            SpellResult spellResult = new SpellResult();
            spellResult.ID = ID;
            return spellResult;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
